export enum CATEGORY_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE'
}

export enum CATEGORY_MODULE {
  SHOP = 'SHOP',
  PAGE = 'PAGE',
  FORUM = 'FORUM',
  JOB = 'JOB',
  COURSE = 'COURSE',
  REPORT = 'REPORT',
  ALL = 'ALL'
}