export enum JOB_TYPE {
  INTERN = 'INTERN',
  PART_TIME = 'PART_TIME',
  FULL_TIME = 'FULL_TIME',
  REMOTE = 'REMOTE',
  FREELANCE = 'FREELANCE'
}

export enum JOB_GENDER {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  BOTH = 'BOTH'
}

export enum SALARY_TYPE {
  HOURLY = 'HOURLY',
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  YEARLY = 'YEARLY'
}

export enum JOB_CAREER {
  MANAGER = 'MANAGER',
  OFFICER = 'OFFICER',
  STUDENT = 'STUDENT',
  EXECUTIVE = 'EXECUTIVE',
  OTHERS = 'OTHERS',
}

export enum JOB_QUALIFICATION {
  CERTIFICATE = 'CERTIFICATE',
  ASSOCIATE_DEGREE = 'ASSOCIATE_DEGREE',
  BACHELOR_DEGREE = 'BACHELOR_DEGREE',
  MASTER_DEGREE = 'MASTER_DEGREE',
  DOCTORATE_DEGREE = 'DOCTORATE_DEGREE'
}