export enum RELATION_TYPE {
  FOLLOW = 'FOLLOW',
  FRIEND = 'FRIEND',
  BLOCKED = 'BLOCKED',
  OWNER = 'OWNER',
  LIKED = 'LIKED'
}

export enum FRIEND_STATUS {
  REQUESTING = 'REQUESTING',
  ACCEPTED = 'ACCEPTED'
}