export enum ModuleName {
  ACTIVITY = 'Activity',
  ADDRESS = 'Address',
  ALBUM = 'Album',
  APPLICANT = 'Applicant',
  BLOG = 'Blog',
  CATEGORY = 'Category',
  CERTIFICATE = 'Certificate',
  CHAT = 'Chat',
  COMMENT = 'Comment',
  COURSE = 'Course',
  EVENT = 'Event',
  FILE = 'File',
  GROUP = 'Group',
  ITEM = 'Item',
  JOB = 'Job',
  LESSON = 'Lesson',
  MEMBER = 'Member',
  MESSAGE = 'Message',
  ORDER = 'Order',
  PAGE = 'Page',
  PARTICIPANT = 'Participant',
  POLICY = 'Policy',
  POST = 'Post',
  PRODUCT = 'Product',
  PROFILE = 'Profile',
  REACT = 'React',
  REEL = 'Reel',
  RELATION = 'Relation',
  REPLY = 'Reply',
  REPORT = 'Report',
  RESPONDED = 'Responded',
  RESUME = 'Resume',
  REVIEW = 'Review',
  UPLOAD = 'Upload',
  USER = 'User',
  VOTE = 'Vote',
  VERIFY = 'Verify',
}

export enum DBName {
  ACTIVITY = 'activity',
  ADDRESS = 'address',
  ALBUM = 'album',
  APPLICANT = 'applicant',
  BLOG = 'blog',
  CATEGORY = 'category',
  CERTIFICATE = 'certificate',
  CHAT = 'chat',
  COMMENT = 'comment',
  COURSE = 'course',
  EVENT = 'event',
  FILE = 'file',
  GROUP = 'group',
  ITEM = 'item',
  JOB = 'job',
  LESSON = 'lesson',
  MEMBER = 'member',
  MESSAGE = 'message',
  ORDER = 'order',
  PARTICIPANT = 'participant',
  PERMISSION = 'permission',
  POLICY = 'policy',
  POST = 'post',
  PRODUCT = 'product',
  PROFILE = 'profile',
  REACT = 'react',
  RELATION = 'relation',
  REPLY = 'reply',
  REPORT = 'report',
  RESPONDED = 'responded',
  RESUME = 'resume',
  REVIEW = 'review',
  ROLE = 'role',
  TAG = 'tag',
  USER = 'user',
  VOTE = 'vote',
  VERIFY = 'verify',
}

export enum Action {
  Manage = 'manage',  // 1
  Create = 'create',  // 2
  Read = 'read',      // 3
  Update = 'update',  // 4
  Delete = 'delete',  // 5
}

export enum SYSTEM_MODULE {
  USER = 'USER',
  SOCIAL = 'SOCIAL',
  SHOP = 'SHOP',
  JOB = 'JOB',
  FORUM = 'FORUM',
  COURSE = 'COURSE',
  CHAT = 'CHAT',
  PACKAGE = 'PACKAGE',
  SETTING = 'SETTING',
  FILE = 'FILE',
}